### ISSUE TITLE
Token expiration

### ISSUE THREAD

**Issue by parras** [BoscoDomingo/SpotifyMatcher#2]
After a certain duration of running the program, the access token to the Spotify API expires. This translates into the following error message:
```
HTTP Error for GET to https://api.spotify.com/v1/search returned 401 due to The access token expired
```
Apparently, instead of trying to renew the token and retrying, the script keeps going over the list of files with the same expired token.

**Comment by BoscoDomingo** [comment]
Hmmm interesting. Truth is the program never does check for token expiration once the connection with your user profile has been set, so I can see how this would happen. It isn't something we ever considered given we didn't expect anyone to run it for such a length of time. I don't recall Spotify even specifying the length of time the token exists for, but I'll work out a quick fix as soon as I have time to do so.

For now though, if you're in a rush, I breaking down your music collection (grab a couple thousand files maximum each time) ought to work and you should also be able to just reuse the playlist ID for all your music to be in the same one if you want that. Thanks for letting us know about the issue!

**Comment by BoscoDomingo** [comment]
https://community.spotify.com/t5/Other-Partners-Web-Player-etc/API-Access-token-expired/m-p/4696421/highlight/true#M62579
They expire after 1 hour. Guess we can set a timer so that the program checks the token around that time and refreshes it should it be expired, for example

**Comment by BoscoDomingo** [comment]
Alright, v1.1 is up and running. It contains what should fix your problem as well as some neat QoL improvements. Enjoy and let me know if any other issues pop up!
